<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MTP_22.11_10-20</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>52801b24-72a1-4c9d-abdb-3009523b4eee</testSuiteGuid>
   <testCaseLink>
      <guid>5efe73e5-9e73-405f-9fd7-fdca312a0d6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Visual_Test_Case_Full_Page - SingleBrowser 11-20</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eda9f1bb-dad4-47bd-a16d-bf76643eeb85</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data_10-20</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7f441db-6b09-417e-8d6b-9d9678721d4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c444600-2f88-4d1a-9e01-a37bc1bdaf2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9848b7ff-5c98-4971-ba93-100da1de002f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
