<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MTP_22.11_110-120</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>248a672e-4d27-465f-a2c4-0ad06b3850c2</testSuiteGuid>
   <testCaseLink>
      <guid>b2dc79c7-f58b-472e-a299-2d32f8fe9c6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Visual_Test_Case_Full_Page - SingleBrowser-110-120</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5cb5a874-b61d-40bb-b6e4-4fad0a544d3f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data-110-120</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>935352b5-5144-4657-be9f-a757a88eba4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a7a985-57eb-411d-b8fe-4a334691e80f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c05f1efa-9173-4289-a8d3-64c89ed829b2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
