<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MTP_22.11_120-130</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>87b27c01-68a7-45d6-9f61-d23de508218a</testSuiteGuid>
   <testCaseLink>
      <guid>b2dc79c7-f58b-472e-a299-2d32f8fe9c6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Visual_Test_Case_Full_Page - SingleBrowser-120-130</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>32a92d12-09fb-435a-b07a-f96f67ff33cd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test_Data-120-130</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f052397-fbeb-4144-ad2a-faab0e777a70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0cf0de4-5f1f-42a9-88a7-9e6938167cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dd8b238-b93a-4e36-a4c7-20005d911e56</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
