<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e20489da-c21e-4a72-885a-e7cb5746fbcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://moleculartargets-qa.ccdi.cancer.gov/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&amp;efoId=EFO_0000621&amp;yAxisScale=linear&amp;includeTumorDesc=primaryOnly')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d766e14-0483-4447-b847-3d173462c293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://moleculartargets-qa.ccdi.cancer.gov/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&amp;efoId=EFO_0000621&amp;yAxisScale=linear&amp;includeTumorDesc=primaryOnly</value>
      <webElementGuid>e4f0b136-98a7-4c3f-9030-8e43c2149f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>792</value>
      <webElementGuid>84fa83de-5675-4c30-a91d-4bc1fa997db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>528</value>
      <webElementGuid>ed7433a3-f5f5-437a-8a6d-e398e0b0725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/img[1]</value>
      <webElementGuid>61ecaf0d-1c65-46dc-b187-69deb3750b90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://moleculartargets-qa.ccdi.cancer.gov/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&amp;efoId=EFO_0000621&amp;yAxisScale=linear&amp;includeTumorDesc=primaryOnly')]</value>
      <webElementGuid>b7356635-7743-467a-828d-f07193658909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b058f10a-1ce7-47cb-a8cd-65bdcaaaf997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://moleculartargets-qa.ccdi.cancer.gov/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&amp;efoId=EFO_0000621&amp;yAxisScale=linear&amp;includeTumorDesc=primaryOnly']</value>
      <webElementGuid>7badc7f4-33bf-447e-918d-a0c38b5b37de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
