<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e20489da-c21e-4a72-885a-e7cb5746fbcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f55f236-2cc9-4c04-8caf-65da88d4e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://moleculartargets-qa.ccdi.cancer.gov/tpm/gene-disease-gtex/plot?ensemblId=ENSG00000171094&amp;efoId=EFO_0000621&amp;yAxisScale=linear&amp;includeTumorDesc=primaryOnly</value>
      <webElementGuid>6fdc152c-63da-4bf3-8f83-d97b047316ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>792</value>
      <webElementGuid>10c983e1-9ea8-430d-812c-17b1780eb512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>528</value>
      <webElementGuid>6b4e5005-0632-4e7a-8123-e99632f70cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/img[1]</value>
      <webElementGuid>71203e69-17f7-4dc8-9fe9-4c3ec15a5776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3924605e-8624-4f5b-8801-90bdbf3bf2da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
